- hosts: master:worker
  no_log: False
  become: yes
  gather_facts: yes
  serial: 25
  roles:
    - common

- hosts: master
  no_log: False
  become: yes
  gather_facts: yes
  serial: 25
  roles:
    - master

- hosts: worker
  no_log: False
  become: yes
  gather_facts: yes
  serial: 25
  roles:
    - worker
