---
# tasks file for cleanhouse

- name : Reset Kubenetes Cluster on All Nodes
  shell : "kubeadm reset -f"

- name : Remove Kubernetes from CentOS 
  yum :
      name : ['kubeadm', 'kubelet', 'kubectl']
      state : absent
  when : ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name : Remove Docker on CentOs 7
  yum : 
     name: ['docker','docker-client','docker-common'] 
     state: absent
  when : ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: Apt-mark unhold kubelet kubeadm kubectl on Ubuntu
  shell: "/usr/bin/apt-mark unhold kubelet kubeadm kubectl"
  when: ansible_distribution == "Ubuntu"

- name : Remove Kubernetes from Ubuntu
  apt :
      name: ['kubeadm', 'kubelet', 'kubectl']
      state : absent
      autoremove: yes
      purge: yes
  when: ansible_distribution == "Ubuntu"

- name : Remove Docker Ubuntu Version docker-ce
  apt :
      name: ['docker-ce', 'docker-engine', 'docker', 'docker.io']
      state: absent
      purge: yes
  when: ansible_distribution == "Ubuntu"

#- name : Remove Docker Ubuntu Version docker.io
#  apt :
#      pkg: docker.io
#      state: absent
#      purge: yes
#      update_cache: true
#  when: ansible_distribution == "Ubuntu"
